import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { SessionProvider } from 'next-auth/react';
import { auth } from '@/auth';
import { Navbar } from '~/navbar/navbar';
import { cn } from '@/lib/utils';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default async function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    const session = await auth();
    return (
        <SessionProvider session={session}>
            <html lang="en">
                <body className={cn("bg-[radial-gradient(ellipse_at_top,_var(--tw-gradient-stops))] from-gray-200 to-slate-400", inter.className)}>
                    <Navbar />
                    {children}
                </body>
            </html>
        </SessionProvider>
    );
}
